# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eb043d9c977170262ee515064c8d912fafdb3214e0a47f41ebd746cda11f7a977feb455756c7eb8250d42810142ddc90b89e7a08ff1ba8c240d89ef94815d4b

test:
  secret_key_base: 051066d5bdb4f524f30f4645073922ba0d67bc143959339badbb193f1de1cb8565b2d7ffecb96834e073ce1604f0da1e5a77cfd44e1b5241059eabb69deca4e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
